# Generated by Django 4.0.6 on 2022-07-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ManyToManyField(to='movies.category', verbose_name='Категория'),
        ),
    ]
