# Generated by Django 4.1 on 2022-08-08 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_rating_options_alter_ratingstar_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='parent',
        ),
    ]
