# Generated by Django 4.1 on 2022-08-12 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_review_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trellers', to='movies.movie')),
            ],
        ),
    ]
