# Generated by Django 4.1 on 2022-08-14 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_treller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AlterModelOptions(
            name='treller',
            options={'verbose_name': 'Треллер', 'verbose_name_plural': 'Треллеры'},
        ),
    ]
